// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_sample_no_roi`, `process_sample`

String greet({required String name}) =>
    RustLib.instance.api.crateApiGstreamerGreet(name: name);

String getGstreamerVersion() =>
    RustLib.instance.api.crateApiGstreamerGetGstreamerVersion();

Future<NativePlayer> createPlayer({required String path}) =>
    RustLib.instance.api.crateApiGstreamerCreatePlayer(path: path);

Future<VideoInfo> getVideoInfo({required String path}) =>
    RustLib.instance.api.crateApiGstreamerGetVideoInfo(path: path);

Future<VideoFrame> getFrame({required String path, Roi? roi, BigInt? timeMs}) =>
    RustLib.instance.api.crateApiGstreamerGetFrame(
      path: path,
      roi: roi,
      timeMs: timeMs,
    );

Future<Roi?> autoDetectRoiForTime({required String path, BigInt? timeMs}) =>
    RustLib.instance.api.crateApiGstreamerAutoDetectRoiForTime(
      path: path,
      timeMs: timeMs,
    );

Future<void> initGstreamer() =>
    RustLib.instance.api.crateApiGstreamerInitGstreamer();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativePlayer>>
abstract class NativePlayer implements RustOpaqueInterface {
  Future<void> pause();

  Future<void> resume();

  Future<void> seek({required BigInt timeMs});

  Future<void> setAutoTracking({required bool enabled});

  Future<void> setRoi({Roi? roi});

  Stream<PlayerEvent> start({Roi? roi, BigInt? startTimeMs});

  Future<void> stop();
}
