// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class CaptionResult {
  final String text;
  final double confidence;
  final BigInt timestampMs;

  const CaptionResult({
    required this.text,
    required this.confidence,
    required this.timestampMs,
  });

  static Future<CaptionResult> default_() =>
      RustLib.instance.api.crateApiModelsCaptionResultDefault();

  @override
  int get hashCode =>
      text.hashCode ^ confidence.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptionResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          confidence == other.confidence &&
          timestampMs == other.timestampMs;
}

@freezed
sealed class PlayerEvent with _$PlayerEvent {
  const PlayerEvent._();

  const factory PlayerEvent.video(VideoFrame field0) = PlayerEvent_Video;
  const factory PlayerEvent.caption(CaptionResult field0) = PlayerEvent_Caption;
}

class Roi {
  final int x;
  final int y;
  final int width;
  final int height;
  final BigInt startTimeMs;
  final BigInt endTimeMs;

  const Roi({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.startTimeMs,
    required this.endTimeMs,
  });

  static Future<Roi> default_() =>
      RustLib.instance.api.crateApiModelsRoiDefault();

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Roi &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs;
}

class VideoFrame {
  final Uint8List pixels;
  final int width;
  final int height;
  final bool isCropped;
  final BigInt timestampMs;

  const VideoFrame({
    required this.pixels,
    required this.width,
    required this.height,
    required this.isCropped,
    required this.timestampMs,
  });

  static Future<VideoFrame> default_() =>
      RustLib.instance.api.crateApiModelsVideoFrameDefault();

  @override
  int get hashCode =>
      pixels.hashCode ^
      width.hashCode ^
      height.hashCode ^
      isCropped.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrame &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          width == other.width &&
          height == other.height &&
          isCropped == other.isCropped &&
          timestampMs == other.timestampMs;
}

class VideoInfo {
  final int width;
  final int height;
  final BigInt durationMs;
  final String format;
  final double fps;

  const VideoInfo({
    required this.width,
    required this.height,
    required this.durationMs,
    required this.format,
    required this.fps,
  });

  static Future<VideoInfo> default_() =>
      RustLib.instance.api.crateApiModelsVideoInfoDefault();

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      format.hashCode ^
      fps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          format == other.format &&
          fps == other.fps;
}
