// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String getGstreamerVersion() =>
    RustLib.instance.api.crateApiSimpleGetGstreamerVersion();

Future<VideoInfo> getVideoInfo({required String path}) =>
    RustLib.instance.api.crateApiSimpleGetVideoInfo(path: path);

Stream<VideoFrame> streamVideo({
  required String path,
  Roi? roi,
  BigInt? startTimeMs,
}) => RustLib.instance.api.crateApiSimpleStreamVideo(
  path: path,
  roi: roi,
  startTimeMs: startTimeMs,
);

Future<VideoFrame> getFirstFrame({required String path, Roi? roi}) =>
    RustLib.instance.api.crateApiSimpleGetFirstFrame(path: path, roi: roi);

Future<void> playVideo({required String path}) =>
    RustLib.instance.api.crateApiSimplePlayVideo(path: path);

class Roi {
  final int x;
  final int y;
  final int width;
  final int height;

  const Roi({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  static Future<Roi> default_() =>
      RustLib.instance.api.crateApiSimpleRoiDefault();

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Roi &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}

class VideoFrame {
  final Uint8List pixels;
  final int width;
  final int height;
  final bool isCropped;
  final BigInt timestampMs;

  const VideoFrame({
    required this.pixels,
    required this.width,
    required this.height,
    required this.isCropped,
    required this.timestampMs,
  });

  static Future<VideoFrame> default_() =>
      RustLib.instance.api.crateApiSimpleVideoFrameDefault();

  @override
  int get hashCode =>
      pixels.hashCode ^
      width.hashCode ^
      height.hashCode ^
      isCropped.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrame &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          width == other.width &&
          height == other.height &&
          isCropped == other.isCropped &&
          timestampMs == other.timestampMs;
}

class VideoInfo {
  final int width;
  final int height;
  final BigInt durationMs;
  final String format;
  final double fps;

  const VideoInfo({
    required this.width,
    required this.height,
    required this.durationMs,
    required this.format,
    required this.fps,
  });

  static Future<VideoInfo> default_() =>
      RustLib.instance.api.crateApiSimpleVideoInfoDefault();

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      format.hashCode ^
      fps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          format == other.format &&
          fps == other.fps;
}
